<?php

namespace AppBundle\Repository;

/**
 * AulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AulaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
    {
         return $this->getEntityManager()
        ->createQuery(
            'SELECT *
            FROM UserBundle:Aula
            
            )'
        ->setParameter('nome',$nome)
        
        ->getResult();
    }
}