<?php

namespace UserBundle\Repository;

/**
 * AulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AulaRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCit (){
        return $elencocitta = $this->getEntityManager()
        ->createQuery (
            'SELECT DISTINCT a.citta FROM UserBundle:Aula a ')
        ->getResult();
    }
}
