<?php

namespace UserBundle\Repository;

/**
 * Eventi_AulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Eventi_AulaRepository extends \Doctrine\ORM\EntityRepository
{
}
