<?php

namespace UserBundle\Repository;

/**
 * EventiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventiRepository extends \Doctrine\ORM\EntityRepository
{
}
