<?php

namespace UserBundle\Repository;

/**
 * InvitatiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitatiRepository extends \Doctrine\ORM\EntityRepository
{
}
