<?php

namespace UserBundle\Repository;

/**
 * sedeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sedeRepository extends \Doctrine\ORM\EntityRepository
{
}
