user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }

home:
    path:     /home
    defaults: { _controller: UserBundle:Home:home }



_event:
    path:     /eventi
    defaults: { _controller: UserBundle:Eventi:Event }

confpren:
    path:     /confpren
    defaults: { _controller: UserBundle:Prenota:confpren }

prenconf:
    path:     /prenconf
    defaults: { _controller: UserBundle:Prenota:prenconf }
